arm_nn_mat_mult_kernel_q7_q15_reordered.c File Reference
arm_nn_mat_mult_kernel_q7_q15_reordered.c File Reference
Functions
q7_t * arm_nn_mat_mult_kernel_q7_q15_reordered (const q7_t *pA, const q15_t *pInBuffer, const uint16_t ch_im_out, const uint16_t numCol_A, const uint16_t bias_shift, const uint16_t out_shift, const q7_t *bias, q7_t *pOut)
Matrix-multiplication function for convolution with re-ordered input.
Function Documentation
arm_nn_mat_mult_kernel_q7_q15_reordered()
q7_t * arm_nn_mat_mult_kernel_q7_q15_reordered (const q7_t * pA, const q15_t * pInBuffer, const uint16_t ch_im_out, const uint16_t numCol_A, const uint16_t bias_shift, const uint16_t out_shift, const q7_t * bias, q7_t * pOut)
Matrix-multiplication function for convolution with reordered columns.
Refer to header file for details.
References arm_nn_read_q15x2_ia(), and NN_ROUND.
Referenced by arm_convolve_1x1_HWC_q7_fast_nonsquare(), arm_convolve_HWC_q7_fast(), and arm_convolve_HWC_q7_fast_nonsquare().