arm_max_pool_s16.c File Reference
arm_max_pool_s16.c File Reference
Functions
static void compare_and_replace_if_larger (int16_t *base, const int16_t *target, int32_t length)
static void clamp_output (int16_t *source, int32_t length, const int16_t act_min, const int16_t act_max)
arm_status arm_max_pool_s16 (const cmsis_nn_context *ctx, const cmsis_nn_pool_params *pool_params, const cmsis_nn_dims *input_dims, const int16_t *src, const cmsis_nn_dims *filter_dims, const cmsis_nn_dims *output_dims, int16_t *dst)
s16 max pooling function.
Function Documentation
clamp_output()
static void clamp_output (int16_t * source, int32_t length, const int16_t act_min, const int16_t act_max) static
References arm_nn_read_q15x2(), arm_nn_write_q15x2_ia(), arm_nnword::half_words, MAX, MIN, and arm_nnword::word.
Referenced by arm_max_pool_s16().
compare_and_replace_if_larger()
static void compare_and_replace_if_larger (int16_t * base, const int16_t * target, int32_t length) static
References arm_nn_read_q15x2(), arm_nn_read_q15x2_ia(), arm_nn_write_q15x2_ia(), arm_nnword::half_words, and arm_nnword::word.
Referenced by arm_max_pool_s16().