/*
 * Copyright (c) 2022, Arm Limited and affiliates.
 * SPDX-License-Identifier: Apache-2.0
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*********************    Autogenerated file. DO NOT EDIT *******************
 * Generated from gen_rgb_cpp.py tool  file.
 * Date: 2022-07-29 17:54:47.690348
 ***************************************************************************/

#include "InputFiles.hpp"

static const char *img_filenames[] =
{
    "test1.bmp",
    "test2.bmp",
    "test3.bmp",
    "test4.bmp",
    "test5.bmp",
    "test6.bmp",
    "test7.bmp",
    "test8.bmp",
    "test9.bmp",
    "test10.bmp",
};

static const uint8_t *img_arrays[] =
{
    im1,
    im2,
    im3,
    im4,
    im5,
    im6,
    im7,
    im8,
    im9,
    im10
};

const char *get_filename(const uint32_t idx)
{
    if (idx < NUMBER_OF_FILES)
    {
        return img_filenames[idx];
    }

    return nullptr;
}


const uint8_t *get_img_array(const uint32_t idx)
{
    if (idx < NUMBER_OF_FILES)
    {
        return img_arrays[idx];
    }

    return nullptr;
}
