sbomType: Product SBOM
include:
  - path: Library/CMSIS
  - path: Library/Commu
  - path: Library/CryptoAccelerator
  - path: Library/Device
  - path: Library/JpegAcceleratorLib
  - path: Library/PowerDeliveryLib
  - path: Library/SmartcardLib
  - path: Library/StdDriver
  - path: Library/Storage
  - path: Library/UsbHostLib
exclude:
  - path: Document/
  - path: SampleCode/
  - path: ThirdParty/
  - path: Tool/
